### ISSUE TITLE
검색한 주소 지도에 표시 하는 방법 문의

### ISSUE THREAD

**Issue by skyjich** [brendaniel/ng2-daum-address#2]
안녕하세요. 
지난번에 다음주소 검색으로 문의를 드렸던 skyjich입니다. 덕분에 주소 검색을 잘 사용하고 있습니다. 
헌데, 제가 초보라.. 다음 주소 표시하는 것은 주소검색에서 힌트를 얻어서 구현을 하긴 했는데. 
리스트를 accordion(리스트 제목을 클릭시 내용이 아래로 펼쳐지는 기능)으로 구현하고, 리스트 타이틀을 클릭하면 해당 상세가 보여지는데, 거기에 주소를 지도로 보여주려고 합니다. 
그런데, 주소가 보면 맨 마지막 리스트 주소가 모든 리스트의 지도에 생성이 됩니다. 
아마도 지도를 보여주는 div tag id가 동일해서 인가 본데. 이것저것 방법을 써봐도 해결이 안되어서. 
이렇게 도움을 구합니다. 조언 부탁드립니다. 

감사합니다.

**Comment by brendaniel** [comment]
@skyjich debug 옵션을 true로 주시면 API의 Response가 console로 출력될 거에요.

[문서상](http://postcode.map.daum.net/guide#attributes) 에는 지도에 표시할만한 고도 위도 정보를 주지 않네요.

모든 리스트의 지도에 생성이 된다는건 잘못 뿌리셨다는 말씀같은데 사진이 없어서 뭔지를 잘 모르겠어요.

**Comment by skyjich** [comment]
아. 다음 map api 중에 주소를 lat, long으로 변환해주고..지도에 표시해 주는 함수를 사용했습니다. 
그래서 입력하는 화면에서 주소검색 해서 나온 주소로.. lat, long 구한다음..지도에 표시를 하는것을 구현했습니다. 헌데. 한 화면에 입력정보를 다 보여주는 accordion 기능을 사용해서 그런지.. 마지막 리스트 주소가 지도에 표시가 되는 상황이 발생하였습니다. 지도 표시는 daum-map.component.ts를 별도 만들어서 리스트 화면에 포함해서 진행을 하고 있어요.. 

[화면사진]
https://drive.google.com/open?id=0B1GdMdtVqlSaNnh3c0JNaTFTNzA
https://drive.google.com/open?id=0B1GdMdtVqlSabXdQT3VlZnRnSnM
https://drive.google.com/open?id=0B1GdMdtVqlSaUDdIUXZPeW16VDQ

[html]

        <div class="mdl-cell mdl-cell--6-col mdl-shadow--1dp" align="center">
          <app-btn-daum-address (result)="setDaumAddressApi($event, carItem)" [options]="daumAddressOptions" mdTooltip="위치검색"></app-btn-daum-address>
          
          <app-daum-map [location]="carItemlocation"></app-daum-map>
        </div>
      </div>

[daum-map.component.ts]

import {
    Component,
    Input,
    ElementRef,
    OnInit,
    ChangeDetectionStrategy,
    Output,
    EventEmitter
} from '@angular/core';
import { Observable } from 'rxjs/Observable';
import {FormControl, Validators} from '@angular/forms';
import { HttpModule, JsonpModule, Http, Jsonp, URLSearchParams } from '@angular/http';
import { AngularFireDatabase, FirebaseListObservable, FirebaseObjectObservable} from 'angularfire2/database';
import * as firebase from 'firebase/app';
import { CarItem } from '../CarItem';

declare var daum: any;
const url = "https://apis.daum.net/maps/maps3.js?apikey=52c5f24c066b8e8f7b0c81bda330b89d&libraries=services";

@Component({
  selector: 'app-daum-map',
  template: `
              <div id="view-map" style="width:100%;height:200px;"></div>
              
              `,
  styleUrls: ['./daum-map.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class DaumMapComponent implements OnInit {

  @Input('location') location: string;
  
  @Output() result = new EventEmitter<Object>();
  
  private el: ElementRef;
  private mapid: string;
  
  bounds_changed(event) {
    console.log(event);
  }
  
  constructor(
    el: ElementRef
  ) { 
    this.el = el;
  }
  
  ngOnInit() {
    this.loadDaumApi().then(()=>{
      console.log('Daum api has been loaded.');
    });
    console.log("input location :"+this.location);
    // var mapid = this.key;
    var term = this.location;
    var mapContainer = document.getElementById('view-map'); // 지도를 표시할 div 
    var mapOption = {
          center: new daum.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
          level: 3 // 지도의 확대 레벨
    };  

    // 지도를 생성합니다    
    var map = new daum.maps.Map(mapContainer, mapOption); 
    
    // 주소-좌표 변환 객체를 생성합니다
    var geocoder = new daum.maps.services.Geocoder();
    
    // 주소로 좌표를 검색합니다
    geocoder.addr2coord(term, function(status, result) {

    // 정상적으로 검색이 완료됐으면 
    if (status === daum.maps.services.Status.OK) {

        var coords = new daum.maps.LatLng(result.addr[0].lat, result.addr[0].lng);

        // 결과값으로 받은 위치를 마커로 표시합니다
        var marker = new daum.maps.Marker({
            map: map,
            position: coords
        });

        // 인포윈도우로 장소에 대한 설명을 표시합니다
        var infowindow = new daum.maps.InfoWindow({
            content: '<div style="width:150px;text-align:center;padding:6px 0;">'+term+'</div>'
        });
        infowindow.open(map, marker);

        // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
        map.setCenter(coords);
    }
    }); 
  }
  
  
  private loadDaumApi(){
    return new Promise((resolve, reject)=> {
      let script = document.createElement('script');
      script.src = url;
      script.type = 'text/javascript';
      script.async = true;
      // script.crossOrigin= 'anonymous';
      this.el.nativeElement.appendChild(script);
      resolve(true);
    });
  }

}

**Comment by brendaniel** [comment]
@skyjich 이 모듈에 대한 오류, 버그 문의 외에는 저도 답변드리기 어렵네요.

**Comment by skyjich** [comment]
아..네..고맙습니다.
